# Generated by Django 4.2.3 on 2023-08-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
